# Site settings
title: Those Who Can't Teach....Code?
header-img: img/home-bg.png
email: mia.balsamo@gmail.com
copyright_name: mbalsamo2
description: > # this means to ignore newlines until "baseurl:"
  The Journey to Code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mbalsamo2
learn_profile: mbalsamo2
email_username: mia.balsamo@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
